<?php
/**
 * Copyright (c) 2026. Volodymyr Hryvinskyi. All rights reserved.
 * Author: Volodymyr Hryvinskyi <volodymyr@hryvinskyi.com>
 * GitHub: https://github.com/hryvinskyi
 */

declare(strict_types=1);

/**
 * @var \Hryvinskyi\Base\Block\Adminhtml\Menu $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

if (!$block->hasItems()) {
    return;
}

$style = '.page-title-wrapper .page-title {
    display: none;
}';

echo $secureRenderer->renderTag('style', [], $style, false);
?>
<div class="admin__action-dropdown-wrap hryvinskyi-core-menu">
    <button
        type="button"
        class="admin__action-dropdown"
        data-mage-init='{"dropdown":{}}'
        data-toggle="dropdown"
        aria-haspopup="true">
        <?= /* @noEscape */ $block->getMenuIcon() ?>
        <span class="admin__action-dropdown-text"><?= $escaper->escapeHtml(__($block->getMenuTitle())) ?></span>
    </button>

    <ul class="admin__action-dropdown-menu">
        <?php foreach ($block->getMenuItems() as $item): ?>
            <?php if ($item->isActive()): ?>
                <li<?= $item->getClass() ? ' class="' . $escaper->escapeHtmlAttr($item->getClass()) . '"' : '' ?>>
                    <a href="<?= $escaper->escapeUrl($item->getUrl()) ?>">
                        <?php if ($item->getIcon()): ?>
                            <span class="menu-item-icon"><?= /* @noEscape */ $item->getIcon() ?></span>
                        <?php endif; ?>
                        <?= $escaper->escapeHtml(__($item->getLabel())) ?>
                    </a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
</div>
